### ISSUE TITLE
Pass exec_wrapper args via pkg_python_app

### ISSUE THREAD

**Issue by ian-h-chamberlain** [128technology/rules_128tech#12]
The only thing blocking the Installer from using `pkg_python_app` is its use of custom args to `exec_wrapper`:

```py
exec_wrapper(
    name = "install128t",
    env = get_python_env(),
    exe = "/usr/bin/nice",
    static_args = [
        "-n",
        "5",
        "/usr/lib/128T-installer/install128t.par",
    ],
)
```

We could add something like `exec_wrapper_kwargs` if we wanted a generic solution for this, although `env` is already passed through as its own argument... so maybe that should just be pulled into the new kwargs with a default set?

**Comment by jacobbogdanov** [comment]
it's a weird use case that we have with the installer... the path that's passed to `static_args` needs to know the name and path to the par, so the two rules are tightly coupled and the caller needs to duplicate some information in two places no matter what.

At that point, rather than `exec_wrapper_kwargs` I'd propose a BYO-exec_wrapper. That way `pkg_python_app` isn't creating the `exec_wrapper`, but the BUILD file creates it and just passes the name into `pkg_python_app`. OR, just tell `pkg_python_app` to not create an exec wrapper and wrap the two into a tar in the BUILD file

**Comment by ian-h-chamberlain** [comment]
So, you're suggesting something like `exec_wrapper = True` and it would just skip the exec wrapper if set to `False`?

That might be a bit simpler, let me see how it looks. I can update my PR if that seems like what we want to do here.
